services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poll-app-app
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: poll_app
      DB_USER: poll_user
      DB_PASS: poll_pass
      APP_ENV: docker
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      - db  # se sua versão aceitar 'condition: service_healthy', pode voltar

  db:
    image: mysql:8.0
    container_name: poll-app-db
    environment:
      MYSQL_DATABASE: poll_app
      MYSQL_USER: poll_user
      MYSQL_PASSWORD: poll_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d:ro
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -ppoll_pass --user=poll_user || exit 1"]
      interval: 7s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:4
    container_name: poll-app-adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data:
